### ISSUE TITLE
Cannot set property url of [object Object] which has only a getter

### ISSUE THREAD

**Issue by jpsala** [adarshpastakia/aurelia-ui-framework#29]
Hi, you have done a beautyfull job, I really love the ui you have done.
I did npm install, then jspm install and for building to be successfull I had to install gulp-rename, it's builds ok but when I run the app I get:
`ERROR [app-router] TypeError: Cannot set property url of [object Object] which has only a getter
    at Object.config.withBaseUrl.withInterceptor.request (http://localhost/aurelia-ui-framework/framework/utils/ui-http-service.js:26:37)
    at eval (http://localhost/aurelia-ui-framework/jspm_packages/npm/aurelia-fetch-client@1.0.0-beta.1.2.0/aurelia-fetch-client.js:258:36)error @ aurelia-logging-console.js:86log @ aurelia-logging.js:41error @ aurelia-logging.js:74processResult @ aurelia-router.js:1658(anonymous function) @ aurelia-router.js:1613
aurelia-logging-console.js:86 ERROR [app-router] Router navigation failed, and no previous location could be restored.`

**Comment by adarshpastakia** [comment]
Fixed. Was trying to replace the url in the request interceptor by passing it through encodeURI.

**Comment by jpsala** [comment]
Excelent! now it works, thanks

What I had to do is
` npm install gulp-rename --save-dev`
Is it ok?

**Comment by jpsala** [comment]
Can I use yout ui without typescript, with only es6?

**Comment by adarshpastakia** [comment]
If you are building the source then yes gulp-rename is needed.
As for es6 it should work fine, when you build the source it should place the compiled framework into a release folder, include that in your es6 project

**Comment by jpsala** [comment]
aha, I understand now, thanks!
